### ISSUE TITLE
OBJ exported from trim_advanced.py example is empty

### ISSUE THREAD

**Issue by virtualritz** [orbingol/NURBS-Python_Examples#3]
I uncommented the export command in the [trim_advanced.py](https://github.com/orbingol/NURBS-Python_Examples/blob/2f5e701e88f498de240ed3695b014472682ca7e9/surface/trimming/trim_advanced.py#L64) example. The resulting `trim_advanced.obj` file is empty apart from the comment at the top:
```
# Generated by geomdl
```

I'm using python 3.7.4 on macOS 10.14.6.

Is this expected/a known limitation?
How can I export a trimmed NURBS with NURBS-Python otherwise?

**Comment by virtualritz** [comment]
I tried exporting as JSON and then converting to OpenNURBS via [rw3dm](https://github.com/orbingol/rw3dm).

When I open the resulting 3DM file in Rhino there seem to be no trim curves. Aka: this also doesn't work unless I miss something.

**Comment by orbingol** [comment]
> When I open the resulting 3DM file in Rhino there seem to be no trim curves. Aka: this also doesn't work unless I miss something.

Unfortunately, this has been an issue for a while ([ref](https://github.com/orbingol/rw3dm/issues/7)). OpenNURBS is a maze when it comes to exporting trimmed surfaces. Still, I was able to come to some point and found that one required API call is missing in OpenNURBS. On the other hand, it exists in Rhino3D SDK (and it is not free). Please refer to `rw3dm` repo for more details.

**Comment by orbingol** [comment]
> I uncommented the export command in the trim_advanced.py example. The resulting trim_advanced.obj file is empty apart from the comment at the top.

I will check this as soon as possible.

**Comment by virtualritz** [comment]
Any update? I have a deadline looming and need to look for a plan b solution otherwise. :)

**Comment by orbingol** [comment]
Please comment out line 58 that calls `trimming.fix_trim_curves` and it should create a non-empty OBJ file. `trimming` module is still experimental and it might cause issues ([docs](https://nurbs-python.readthedocs.io/en/latest/module_trimming.html))

**Comment by virtualritz** [comment]
I tried uncommenting line 58 before making this ticket. Sorry for not mentioning it. It doesn't change anything – the resulting OBJ is still empty.

**Comment by orbingol** [comment]
> I tried uncommenting line 58 before making this ticket. Sorry for not mentioning it. It doesn't change anything – the resulting OBJ is still empty.

Would you test it again after pulling the new changes from the examples repo? I have updated the `master` branch, it seems to work fine for me (tested with a clean conda environment + geomdl 5.2.9)

**Comment by virtualritz** [comment]
Works! The OBJ is has data now and the data is good. Thank you so much!
